# Generated by Django 4.0.4 on 2022-06-26 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalcRights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('can_calc_conics', 'Allowed to calculate conics'),),
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
