# Generated by Django 4.0.4 on 2022-06-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curveapp', '0002_conicselection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conicselection',
            name='a',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='conicselection',
            name='b',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='conicselection',
            name='c',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='conicselection',
            name='d',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='conicselection',
            name='e',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='conicselection',
            name='f',
            field=models.IntegerField(),
        ),
    ]
