# Generated by Django 4.0.4 on 2022-06-20 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curveapp', '0003_alter_conicselection_a_alter_conicselection_b_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conicselection',
            name='t',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
