# Generated by Django 4.0.4 on 2022-06-20 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curveapp', '0004_conicselection_t'),
    ]

    operations = [
        migrations.DeleteModel(
            name='circleinput',
        ),
        migrations.DeleteModel(
            name='ellipseinput',
        ),
        migrations.AlterField(
            model_name='conicselection',
            name='a',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='conicselection',
            name='b',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='conicselection',
            name='c',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='conicselection',
            name='d',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='conicselection',
            name='e',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='conicselection',
            name='f',
            field=models.FloatField(),
        ),
    ]
